site_name: Sparrow SMS API Documentation
site_url: http://api.sparrowsms.com
repo_url: http://github.com/sparrowsms/apidocs
site_description: Sparrow SMS Official Developers API.
site_author: Sparrow SMS (@sparrowsms)
theme: readthedocs
pages:
 - [index.md, Home]
 - [documentation.md, Documentation]
 - [examples.md, Examples]
