site_name: Sparrow SMS
site_url: http://api.sparrowsms.com
repo_url: http://github.com/sparrowsms/apidocs
site_description: Sparrow SMS Official Developers API.
site_author: Sparrow SMS (@sparrowsms)
theme: ''
theme_dir: 'readthedocs'
include_nav: True

pages:
 - ['index.md', 'Home']
 - ['documentation.md', 'Documentation']
 - ['outgoing_sendsms.md', 'Push SMS (MT)']
 - ['outgoing_credits.md', 'Credits']
 - ['incoming.md', 'Pull SMS (MO)']
 - ['examples.md', 'Examples']
 - ['examples_outgoing.md', 'Push SMS (MT) Examples']
 - ['examples_credits.md', 'Credits Examples']
 - ['examples_incoming.md', 'Pull SMS (MO) Examples']